### ISSUE TITLE
WebRTC session never ends

### ISSUE THREAD

**Issue by samueljun** [MyPureCloud/purecloud-webrtc-sdk#5]
Is this expected behavior? The WebRTC session never seems to end, despite ending the Conversation through the Public REST API as well as hitting the `sdk.endSession()` function.

**Comment by xdumaine** [comment]
@samueljun The session is expected to end. It does seem to work in the sample app.  You should be able to do `sdk.endSession({ conversationId })` - maybe you're making this call with the wrong id?

Can you share your code for listening for the sessionEnd event and for ending the conversation, and possibly also any responses you get from the API when doing this? 

If using `sdk.endSession` you should see a `GET` to `api/v2/conversations/calls/{conversationId}` and a `PATCH` to `/api/v2/conversations/calls/{conversationId}/participants/{participantId}`

**Comment by samueljun** [comment]
When I call `sdk.endSession({ conversationId })`, I see that that the Participant disconnects from the Conversation properly from the incoming WebSocket notification. However I never see the `"sessionEnded"` event from the WebRTC SDK. I have a simple console.log for this event but I never see it.

```
  sdk.on("sessionEnded", (session, reason) => {
    console.log("=== EVENT sessionEnded", session, reason);
  });
```

Similarly, the MediaStream never ends either as indicated by the Chrome red recording icon. I never see the red recording icon disappear. The red recording icon never disappears from the [PureCloud web app](https://apps.mypurecloud.com/) either even when all of the interactions are over.

<img width="167" alt="screen shot 2018-07-16 at 2 49 21 pm" src="https://user-images.githubusercontent.com/1808588/42785463-7153f1a6-8907-11e8-8578-81330c1b8944.png">

**Comment by xdumaine** [comment]
@samueljun Can you please make sure your station is not configured for persistent connection? That would explain both the sessionEnded event not firing and the red recording icon not disappearing from the PureCloud web app.

**Comment by xdumaine** [comment]
The media stream not stopping with the SDK is a separate issue and I should have a fix up for that soon.

**Comment by xdumaine** [comment]
@samueljun have you been able to verify if you're using a persistent connection with your station? From the tests we run using this, I'm fairly confident that the sessionEnded event will fire as long as the station isn't configured for persistent connection. Let me know if you're having any problems. Also, if you'd like to have a dev session to work through any issues, we can do that too.

**Comment by samueljun** [comment]
Hmm I'm not familiar with the "persistent connection" setting. Where do I change that setting?

**Comment by samueljun** [comment]
Nvm found it! That did the trick. Feel free to close this issue now 👍

**Comment by xdumaine** [comment]
Awesome, thanks for following up.
