### ISSUE TITLE
Production Error "Uncaught TypeError: r.emit is not a function"

### ISSUE THREAD

**Issue by samueljun** [MyPureCloud/purecloud-webrtc-sdk#9]
I'm currently seeing a production-only TypeError when initializing the SDK. Local doesn't have any issues but when transpiling and bundling using browserify (+ babelify + uglify), the error pops up.

Here is the type error that is being thrown in the console:

```js
purecloud-webrtc-sdk.js:1 Uncaught TypeError: r.emit is not a function
    at XMLHttpRequest.t.onreadystatechange (purecloud-webrtc-sdk.js:1)
t.onreadystatechange @ purecloud-webrtc-sdk.js:1
XMLHttpRequest.send (async)
u._end @ purecloud-webrtc-sdk.js:1
u.end @ purecloud-webrtc-sdk.js:1
(anonymous) @ purecloud-webrtc-sdk.js:1
t @ es6-shim.js:1663
r.then @ purecloud-webrtc-sdk.js:1
value @ purecloud-webrtc-sdk.js:1
value @ index.js:36                        // The line here is _sdk.intitialize()_
commitLifeCycles @ react-dom.production.min.js:159
w @ react-dom.production.min.js:185
_ @ react-dom.production.min.js:182
y @ react-dom.production.min.js:181
b @ react-dom.production.min.js:181
h @ react-dom.production.min.js:180
c @ react-dom.production.min.js:179
t @ react-dom.production.min.js:190
updateContainer @ react-dom.production.min.js:191
nn.render @ react-dom.production.min.js:228
(anonymous) @ react-dom.production.min.js:242
unbatchedUpdates @ react-dom.production.min.js:188
sn @ react-dom.production.min.js:242
render @ react-dom.production.min.js:244
354.../platform/teams/u4b/utils/constants @ routes.jsx:252
o @ _prelude.js:1
(anonymous) @ _prelude.js:1
366../components/routes.jsx @ main.js:48971
o @ _prelude.js:1
e @ _prelude.js:1
(anonymous) @ _prelude.js:1
```

If I manually go into `node_modules/purecloud-webrtc-sdk/web/purecloud-webrtc-sdk.js` to format the file with Prettier for a better stack trace, it looks like the line that's being thrown is here:

```js
        (_.prototype._end = function() {
          var t = this,
            e = (this.xhr = l.getXHR()),
            n = this._formData || this._data;
          this._setTimeouts(),
            (e.onreadystatechange = function() {
              var n = e.readyState;
              if (
                (n >= 2 &&
                  t._responseTimeoutTimer &&
                  clearTimeout(t._responseTimeoutTimer),
                4 == n)
              ) {
                var r;
                try {
                  r = e.status;
                } catch (t) {
                  r = 0;
                }
                if (!r) {
                  if (t.timedout || t._aborted) return;
                  return t.crossDomainError();
                }
                t.emit("end"); // LINE 831 This is where emit is not a function
              }
            });
          var r = function(e, n) {
            n.total > 0 && (n.percent = (n.loaded / n.total) * 100),
              (n.direction = e),
              t.emit("progress", n);
          };

```

I'm still debugging and trying to isolate the issue but was wondering if you had seen this before and knew what the issue is.

**Comment by xdumaine** [comment]
I'm not having luck reproducing this one so far. Do you have your browserify config set up to ignore uglifying this module, since it's already bundled? We could publish an unminified/uglified version if it's a problem with that, which I've seen before on other modules. Alternatively, you could import from source instead of the bundle. I'll keep working on a repro of this and get back to you if I find anything.

**Comment by samueljun** [comment]
Hey @xdumaine I was able to repro using `gulp-uglify@1.5.4` which is the currently what our build tools are using. I was also able to repro the issue with `gulp-uglify` and `purecloud-webrtc-sdk` on a clean project as well.

I haven't done any deeper digging to see if this is a bug with `gulp-uglify@1.5.4`, but thankfully we have a work around by importing the CDN library using the `<script>` tag.

**Comment by xdumaine** [comment]
Cool, thanks for the extra info, I'll work up a sample.

**Comment by xdumaine** [comment]
That was it. I did a sample with `gulp-uglify@1.5.4` and got the error. With latest 2.x and 3.x branches of gulp-uglify, I do not get the error. I would look into upgrading gulp-uglify.

**Comment by samueljun** [comment]
Thanks for testing the other versions! I appreciate the quick response and support. It is unfortunately time-prohibitive for us to upgrade at the moment. But I'll look into upgrading in the future. Thanks!

**Comment by xdumaine** [comment]
Sounds good.
